AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: java8
    MemorySize: 256

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  CreateEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.EmployeeHandler::create
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: EmployeeTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Employee
            Method: POST
            RestApiId:
              Ref: RestApi

  GetEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.EmployeeHandler::read
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: EmployeeTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Employee/{id}
            Method: GET
            RestApiId:
              Ref: RestApi

  EmployeeTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: Employee
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:

  RestApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://RestApi.execute-api.${AWS::Region}.amazonaws.com/Prod/employee/"
  CreateEmployeeFunction:
    Description: "CreateEmployeeFunctionARN"
    Value: !GetAtt CreateEmployeeFunction.Arn
  CreateEmployeeFunctionIamRole:
    Description: "Implicit IAM Role created for CreateEmployeeFunction"
    Value: !GetAtt CreateEmployeeFunctionRole.Arn
  GetEmployeeFunction:
    Description: "CreateEmployeeFunctionARN"
    Value: !GetAtt GetEmployeeFunction.Arn
  GetEmployeeFunctionIamRole:
    Description: "Implicit IAM Role created for CreateEmployeeFunction"
    Value: !GetAtt GetEmployeeFunctionRole.Arn