AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
Employee CRUD

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: java8
    MemorySize: 256

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: employee-crud-api-${StageName}
      StageName:
        Ref: StageName

  CreateEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: employee-crud-create-employee-${StageName}
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.EmployeeHandler::create
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: Employee
      Events:
        List:
          Type: Api
          Properties:
            Path: /Employee
            Method: POST
            RestApiId:
              Ref: RestApi

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: employee-crud-read-employee-${StageName}
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.EmployeeHandler::read
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: Employee
      Events:
        List:
          Type: Api
          Properties:
            Path: /Employee/{id}
            Method: GET
            RestApiId:
              Ref: RestApi

  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: employee-crud-employee
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1